name: Local Build & Test
on:
  - push
  - pull_request
env:
  IMAGE: ghcr.io/makisuo/postgres
  #BASE_IMAGE: public.ecr.aws/docker/library/postgres
  BASE_IMAGE: postgres
jobs:
  build-only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            version: "13-alpine"

          - distro: alpine
            version: "14-alpine"

          - distro: alpine
            version: "15-alpine"

          - distro: alpine
            version: "16-alpine"

          - distro: alpine
            version: "17-alpine"

          - distro: debian
            version: "13"

          - distro: debian
            version: "14"

          - distro: debian
            version: "15"

          - distro: debian
            version: "16"

          - distro: debian
            version: "17"

          - distro: debian
            version: latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build --rm -f ${{ matrix.distro }}.Dockerfile
               --build-arg base_image=${{ env.BASE_IMAGE }}:${{ matrix.version }}
               --tag ${{ env.IMAGE }}:${{ matrix.version }}
               .

      - name: Install Docker Compose
        uses: withlogicco/setup-compose-cli@v1

      - name: Test alpine image
        env:
          IMAGE: ${{ env.IMAGE }}:${{ matrix.version }}
        run: docker compose -f docker-compose.test.yml run sut
